//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snake_Game.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Snake_Game\\Snake_Game_Controls.xml")]
        public string controlsXmlPath {
            get {
                return ((string)(this["controlsXmlPath"]));
            }
            set {
                this["controlsXmlPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Snake_Game\\Snake_Game_Score.xml")]
        public string scoreXmlPath {
            get {
                return ((string)(this["scoreXmlPath"]));
            }
            set {
                this["scoreXmlPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Snake_Game\\Snake_Game_Settings.xml")]
        public string settingsXmlPath {
            get {
                return ((string)(this["settingsXmlPath"]));
            }
            set {
                this["settingsXmlPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Snake_Game\\gameSprite.png")]
        public string gameSpritePath {
            get {
                return ((string)(this["gameSpritePath"]));
            }
            set {
                this["gameSpritePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Snake_Game\\gameSpritePUpX2.png")]
        public string gameSpritePUpX2Path {
            get {
                return ((string)(this["gameSpritePUpX2Path"]));
            }
            set {
                this["gameSpritePUpX2Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Snake_Game\\gameSpritePUpPointTick.png")]
        public string gameSpritePUpPointTickPath {
            get {
                return ((string)(this["gameSpritePUpPointTickPath"]));
            }
            set {
                this["gameSpritePUpPointTickPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Snake_Game\\gameSpritePUpSlowmotion.png")]
        public string gameSpritePUpSlowmotionPath {
            get {
                return ((string)(this["gameSpritePUpSlowmotionPath"]));
            }
            set {
                this["gameSpritePUpSlowmotionPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Snake_Game\\gameSpritePUpNoclip.png")]
        public string gameSpritePUpNoclipPath {
            get {
                return ((string)(this["gameSpritePUpNoclipPath"]));
            }
            set {
                this["gameSpritePUpNoclipPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Snake_Game\\gameSpritePUpX2PointTick.png")]
        public string gameSpritePUpX2PointTickPath {
            get {
                return ((string)(this["gameSpritePUpX2PointTickPath"]));
            }
            set {
                this["gameSpritePUpX2PointTickPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Snake_Game\\gameSpritePUpX2Slowmotion.png")]
        public string gameSpritePUpX2SlowmotionPath {
            get {
                return ((string)(this["gameSpritePUpX2SlowmotionPath"]));
            }
            set {
                this["gameSpritePUpX2SlowmotionPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Snake_Game\\gameSpritePUpX2Noclip.png")]
        public string gameSpritePUpX2NoclipPath {
            get {
                return ((string)(this["gameSpritePUpX2NoclipPath"]));
            }
            set {
                this["gameSpritePUpX2NoclipPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Snake_Game\\gameSpritePUpPointTickSlowmotion.png")]
        public string gameSpritePUpPointTickSlowmotionPath {
            get {
                return ((string)(this["gameSpritePUpPointTickSlowmotionPath"]));
            }
            set {
                this["gameSpritePUpPointTickSlowmotionPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Snake_Game\\gameSpritePUpPointTickNoclip.png")]
        public string gameSpritePUpPointTickNoclipPath {
            get {
                return ((string)(this["gameSpritePUpPointTickNoclipPath"]));
            }
            set {
                this["gameSpritePUpPointTickNoclipPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Snake_Game\\gameSpritePUpSlowmotionNoclip.png")]
        public string gameSpritePUpSlowmotionNoclipPath {
            get {
                return ((string)(this["gameSpritePUpSlowmotionNoclipPath"]));
            }
            set {
                this["gameSpritePUpSlowmotionNoclipPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingsDeveloperXmlPath {
            get {
                return ((string)(this["settingsDeveloperXmlPath"]));
            }
            set {
                this["settingsDeveloperXmlPath"] = value;
            }
        }
    }
}
